### ISSUE TITLE
Neo4j相关问题求解

### ISSUE THREAD

**Issue by WenTingTseng** [liuhuanyong/QASystemOnMedicalKG#35]
![擷取](https://user-images.githubusercontent.com/32416416/81496373-e24db480-92e9-11ea-9412-8a9eb99667f7.JPG)
请问这个要如何处理似乎是neo4j的问题?
另外作者说到
配置要求：要求配置neo4j数据库及相应的python依赖包。neo4j数据库用户名密码记住，并修改相应文件。是什麼意思

**Comment by maxoyed** [comment]
1. 安装python依赖
```shell
pip install py2neo pyahocorasick
```
2. 安装neo4j
这里推荐使用docker的方式安装，参考文档：[neo4j Docker Official Images](https://hub.docker.com/_/neo4j/?tab=description)
以下为docker-compose配置
```yml
version: "3"
services:
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/lhy123 # 用户名/密码 需要在build_medicalgraph.py和answer_search.py两个文件中，将Graph的user, password修改为这里设置的值，且用户名必须为neo4j，否则neo4j初始化时会报错
```
3. 导入节点和关系
修改`build_medicalgraph.py`的main函数代码并执行`python build_medicalgraph.py` 
```python
if __name__ == '__main__':
    handler = MedicalGraph()
    handler.create_graphnodes()
    handler.create_graphrels()
```
4. 启动对话机器人
```shell
python answer_search.py
```

效果截图
![image](https://user-images.githubusercontent.com/25519245/81497338-61de8200-92f0-11ea-97b3-9756a83d45be.png)

neo4j部分数据可视化
![image](https://user-images.githubusercontent.com/25519245/81497350-7589e880-92f0-11ea-9b17-006bd77cac38.png)
